export const   careerLevelList = [
    'Student',
    'Entry Level',
    'Experienced',
    'Manager',
    'Senior Management',
    'Not specified',
  ];

export const  experienceTypeList = [
    'Full Time',
    'Part Time',
    'Freelance',
    'Internship',
    'Volunteering',
    'Student Activity',
  ];
  export const  jobTypeList = [
    'Full Time',
    'Part Time',
    'Freelance',
    'Internship',
    'Temporary',
    'Shift Based',
    'Work From Home',
    'Volunteering',
    'Student Activity',
  ];
export const  categoriesList = [
    'Analyst/Research',
    'Administration',
    'Accounting/Finance',
    ' Banking',
    ' C - Level Executive / GM / Director',
    ' Creative / Design / Art',
    ' Business Development',
    ' Education / Teaching',
    ' Engineering - Oil & Gas / Energy',
    ' Engineering - Mechanical / Electrical',
    ' Engineering - Construction / Civil / Architecture',
    ' Engineering - Other',
    ' Fashion',
    ' Engineering - Telecom / Technology',
    ' Human Resources',
    ' Hospitality / Hotels / Food Services',
    ' Installation / Maintenance / Repair',
    ' Logistics / Supply Chain',
    ' Legal',
    ' Manufacturing / Production',
    ' Media / Journalism / Publishing',
    ' Marketing / PR / Advertising',
    ' IT / Software Development',
    ' Medical / Healthcare',
    ' Other',
    ' Pharmaceutical',
    ' Operations / Management',
    ' Project / Program Management',
    ' Purchasing / Procurement',
    ' Sales / Retail',
    ' R & D / Science',
    ' Strategy / Consulting',
    ' Tourism / Travel',
    ' Training / Instructor',
    ' Writing / Editorial',
    ' Sports and Leisure',
    ' Quality',
    ' Customer Service / Support',
  ];
export const yearsOfExperienceList = [
    'No Experience',
    'Less than 1 Year',
    '1 Year',
    '2 Years',
    '3 Years',
    '4 Years',
    '5 Years',
    '6 Years',
    '7 Years',
    '8 Years',
    '9 Years',
    '10 Years',
    '11 Years',
    '12 Years',
    '13 Years',
    '14 Years',
    '15 Years',
    'More than 15 Years',
  ];