export const gradeList = [
  'A / Excellent / 85-100%',
  'B / Very Good / 75-84%',
  'C / Good / 65-74%',
  'D / Fair / 50-64%',
  'Not specified',
];
export const careerLevelList = [
  'Student',
  'Entry Level',
  'Experienced',
  'Manager',
  'Senior Management',
  'Not specified',
];
export const educationLevelList = [
  "Bachelor's Degree",
  "Master's Degree",
  'Doctorate Degree',
  'High School',
  'Vocational',
  'Diploma',
];

export const experienceTypeList = [
  'Full Time',
  'Part Time',
  'Freelance',
  'Internship',
  'Volunteering',
  'Student Activity',
];
export const jobTypeList = [
  'Full Time',
  'Part Time',
  'Freelance',
  'Internship',
  'Temporary',
  'Shift Based',
  'Work From Home',
  'Volunteering',
  'Student Activity',
];
export const categoriesList = [
  'Analyst/Research',
  'Administration',
  'Accounting/Finance',
  ' Banking',
  ' C - Level Executive / GM / Director',
  ' Creative / Design / Art',
  ' Business Development',
  ' Education / Teaching',
  ' Engineering - Oil & Gas / Energy',
  ' Engineering - Mechanical / Electrical',
  ' Engineering - Construction / Civil / Architecture',
  ' Engineering - Other',
  ' Fashion',
  ' Engineering - Telecom / Technology',
  ' Human Resources',
  ' Hospitality / Hotels / Food Services',
  ' Installation / Maintenance / Repair',
  ' Logistics / Supply Chain',
  ' Legal',
  ' Manufacturing / Production',
  ' Media / Journalism / Publishing',
  ' Marketing / PR / Advertising',
  ' IT / Software Development',
  ' Medical / Healthcare',
  ' Other',
  ' Pharmaceutical',
  ' Operations / Management',
  ' Project / Program Management',
  ' Purchasing / Procurement',
  ' Sales / Retail',
  ' R & D / Science',
  ' Strategy / Consulting',
  ' Tourism / Travel',
  ' Training / Instructor',
  ' Writing / Editorial',
  ' Sports and Leisure',
  ' Quality',
  ' Customer Service / Support',
];
export const yearsOfExperienceList = [
  'No Experience',
  'Less than 1 Year',
  '1 Year',
  '2 Years',
  '3 Years',
  '4 Years',
  '5 Years',
  '6 Years',
  '7 Years',
  '8 Years',
  '9 Years',
  '10 Years',
  '11 Years',
  '12 Years',
  '13 Years',
  '14 Years',
  '15 Years',
  'More than 15 Years',
];

export const universitiesAndInstitutionsList = [
  'Ain Shams University',
  'Alexandria University',
  'Assiut University',
  'Cairo University',
  'Helwan University',
  'Mansoura University',
  'Minia University',
  'Suez Canal University',
  'South Valley University',
  'Tanta University',
  'Zagazig University',
  'Beni Suef University',
  'Fayoum University',
  'Ismailia University',
  'Sohag University',
  'Suez University',
  'New Valley University',
  'Sinai University',
  'Egypt Japan University of Science and Technology',
  'Egyptian E-learning University',
  'Heliopolis University',
  'Pharos University in Alexandria',
  'New Giza University',
  'Deraya University',
  'Cairo Sadat Academy for Management Sciences',
  'Shorouk Academy',
  'Canadian International University',
  'Institute of Aviation Engineering and Technology',
  'Culture & Science City',
  'Higher Institute of Engineering and Technology in Kafr Elsheikh',
  'Higher Technological Institute',
  'Alexandria Higher Institute of Engineering and Technology',
  'Future Academy',
  'Al Alson Higher Institute',
  'Technical College of El-Mahalla El-Kubra',
  'Technical College of Kafr El-Sheikh',
  'Technical College of Tanta',
  'Technical College of Helwan',
  'Technical College of Mansoura',
  'Vocational Training Center for Electricity and Electronics',
  'Vocational Training Center for Mechanical Engineering',
  'Vocational Training Center for Information Technology',
  'Vocational Training Center for Tourism and Hotel Management',
  'Vocational Training Center for Agriculture',
  'Arab Academy for Science, Technology and Maritime Transport (AAST)',
  'Helwan University for Science and Technology (HWUST)',
  'The British University in Egypt - El Sheikh Zayed (BUE-ESZ)',
  'The British University in Egypt - El Shorouk City (BUE-ESC)',
  'Delta University for Science and Technology (DUST)',
  'Egyptian E-learning University (EELU)',
  'Newgiza University (NGU)',
  'Modern University for Technology and Information (MTI)',
  'The British University in Egypt - El Gouna (BUE-EG)',
  'Toronto Metropolitan University (TMU)',
  'University of Prince Edward Island (UPEI)',
  'Rennes School of Business (RSB)',
  'Ecole Supérieure Libre des Sciences Commerciales Appliquées (ESCA)',
  'Nile University (NU)',
  'Future University in Egypt (FUE)',
];
